"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  FileText,
  User,
  Stethoscope,
  Download,
  CheckCircle,
  ArrowRight,
  Clock,
  Loader2,
  RotateCcw,
  Sparkles
} from "lucide-react";

export function InteractiveDemo() {
  const [currentStep, setCurrentStep] = useState(1);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState("");

  // Form data
  const [formData, setFormData] = useState({
    template: "chest-ct",
    patientName: "John Doe",
    age: "45",
    gender: "Male",
    clinicalHistory: "Chronic cough, rule out malignancy",
    findings: "Small nodule in right upper lobe, 8mm, spiculated margins, no lymphadenopathy"
  });

  // Sample generated report
  const sampleReport = `CHEST CT WITH CONTRAST

PATIENT INFORMATION:
Name: ${formData.patientName}
Age: ${formData.age} years
Gender: ${formData.gender}

CLINICAL INDICATION:
${formData.clinicalHistory}

TECHNIQUE:
Axial CT images of the chest were obtained with intravenous contrast administration.

FINDINGS:

Lungs:
A small spiculated nodule measuring 8 mm is identified in the right upper lobe at the level of segment 1b. The nodule demonstrates irregular margins with peripheral spiculation, concerning for malignancy. No additional pulmonary nodules are identified. The remainder of the lung parenchyma demonstrates normal attenuation without evidence of consolidation, ground-glass opacities, or interstitial disease.

Mediastinum:
The mediastinal and hilar lymph nodes are normal in size and morphology. No pathologic lymphadenopathy is present.

Pleura:
No pleural effusion or pneumothorax is identified.

Heart and Great Vessels:
The heart is normal in size. The aorta and pulmonary arteries are unremarkable.

Chest Wall and Soft Tissues:
The visualized chest wall and soft tissues are unremarkable.

IMPRESSION:
1. 8 mm spiculated nodule in the right upper lobe (segment 1b), concerning for primary lung malignancy. Recommend PET-CT for further evaluation and staging.
2. No evidence of lymphadenopathy or distant metastatic disease in the imaged field.

RECOMMENDATION:
Follow-up with PET-CT scan and possible tissue diagnosis via CT-guided biopsy or bronchoscopy.

---
Report generated by Radly AI
Validated for clinical accuracy`;

  const handleNext = () => {
    if (currentStep < 4) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handleBack = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handleGenerate = () => {
    setIsGenerating(true);
    // Simulate AI processing
    setTimeout(() => {
      setGeneratedReport(sampleReport);
      setIsGenerating(false);
      setCurrentStep(4);
    }, 3000);
  };

  const handleDownload = () => {
    // Simulate download
    const blob = new Blob([generatedReport], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'sample-radiology-report.txt';
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  const handleReset = () => {
    setCurrentStep(1);
    setGeneratedReport("");
    setFormData({
      template: "chest-ct",
      patientName: "John Doe",
      age: "45",
      gender: "Male",
      clinicalHistory: "Chronic cough, rule out malignancy",
      findings: "Small nodule in right upper lobe, 8mm, spiculated margins, no lymphadenopathy"
    });
  };

  return (
    <div className="w-full">
      {/* Progress Bar */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-4">
          {[1, 2, 3, 4].map((step) => (
            <div key={step} className="flex items-center flex-1">
              <div className="flex items-center flex-col">
                <div
                  className={`w-10 h-10 rounded-full flex items-center justify-center font-bold transition-all ${
                    currentStep >= step
                      ? "bg-gradient-to-br from-green-500 to-green-400 text-white shadow-lg"
                      : "bg-gray-200 text-gray-500"
                  }`}
                >
                  {step}
                </div>
                <span className="text-xs mt-2 text-gray-600 font-medium">
                  {step === 1 && "Template"}
                  {step === 2 && "Patient"}
                  {step === 3 && "Findings"}
                  {step === 4 && "Export"}
                </span>
              </div>
              {step < 4 && (
                <div
                  className={`h-1 flex-1 mx-2 rounded transition-all ${
                    currentStep > step ? "bg-green-500" : "bg-gray-200"
                  }`}
                />
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Step Content */}
      <AnimatePresence mode="wait">
        {/* Step 1: Template Selection */}
        {currentStep === 1 && (
          <motion.div
            key="step1"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            <Card className="border-2 border-purple-200">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <FileText className="w-6 h-6 text-purple-600" />
                  Step 1: Choose Template
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="template">Select Template</Label>
                  <Select
                    value={formData.template}
                    onValueChange={(value) => setFormData({ ...formData, template: value })}
                  >
                    <SelectTrigger id="template">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="chest-ct">Chest CT</SelectItem>
                      <SelectItem value="brain-mri">Brain MRI</SelectItem>
                      <SelectItem value="abdomen-ct">Abdomen CT</SelectItem>
                      <SelectItem value="chest-xray">Chest X-Ray</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
                  <p className="text-sm text-gray-700">
                    <span className="font-semibold text-purple-700">Selected:</span> Chest CT - Standard protocol with contrast
                  </p>
                  <p className="text-xs text-gray-600 mt-2">
                    This template follows Lung-RADS classification standards
                  </p>
                </div>

                <div className="bg-orange-50 border-l-4 border-orange-500 p-3 rounded">
                  <p className="text-sm text-gray-700">
                    <span className="font-semibold text-orange-700">💡 Pro Tip:</span> In the real app, click the ⚙️ Settings icon on any template to add custom instructions like &quot;always mention lymphadenopathy&quot; - Radly will remember your preferences forever!
                  </p>
                </div>

                <div className="flex justify-end">
                  <Button onClick={handleNext} className="bg-purple-600 hover:bg-purple-700">
                    Next: Patient Info
                    <ArrowRight className="ml-2 w-4 h-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {/* Step 2: Patient Information */}
        {currentStep === 2 && (
          <motion.div
            key="step2"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            <Card className="border-2 border-blue-200">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <User className="w-6 h-6 text-blue-600" />
                  Step 2: Patient Information
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="patientName">Patient Name</Label>
                    <Input
                      id="patientName"
                      value={formData.patientName}
                      onChange={(e) => setFormData({ ...formData, patientName: e.target.value })}
                      placeholder="John Doe"
                    />
                  </div>
                  <div>
                    <Label htmlFor="age">Age</Label>
                    <Input
                      id="age"
                      type="number"
                      value={formData.age}
                      onChange={(e) => setFormData({ ...formData, age: e.target.value })}
                      placeholder="45"
                    />
                  </div>
                </div>
                <div>
                  <Label htmlFor="gender">Gender</Label>
                  <Select
                    value={formData.gender}
                    onValueChange={(value) => setFormData({ ...formData, gender: value })}
                  >
                    <SelectTrigger id="gender">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Male">Male</SelectItem>
                      <SelectItem value="Female">Female</SelectItem>
                      <SelectItem value="Other">Other</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="clinicalHistory">Clinical History / Indication</Label>
                  <Textarea
                    id="clinicalHistory"
                    value={formData.clinicalHistory}
                    onChange={(e) => setFormData({ ...formData, clinicalHistory: e.target.value })}
                    placeholder="Chronic cough, rule out malignancy"
                    rows={3}
                  />
                </div>
                <div className="flex justify-between">
                  <Button onClick={handleBack} variant="outline">
                    Back
                  </Button>
                  <Button onClick={handleNext} className="bg-blue-600 hover:bg-blue-700">
                    Next: Findings
                    <ArrowRight className="ml-2 w-4 h-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {/* Step 3: Findings */}
        {currentStep === 3 && (
          <motion.div
            key="step3"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            <Card className="border-2 border-green-200">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <Stethoscope className="w-6 h-6 text-green-600" />
                  Step 3: Enter Findings
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="findings">Describe Your Findings</Label>
                  <Textarea
                    id="findings"
                    value={formData.findings}
                    onChange={(e) => setFormData({ ...formData, findings: e.target.value })}
                    placeholder="Small nodule in right upper lobe, 8mm, spiculated margins..."
                    rows={6}
                    className="font-mono text-sm"
                  />
                  <p className="text-xs text-gray-600 mt-2">
                    Use natural language - our AI will structure it professionally
                  </p>
                </div>

                <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                  <div className="flex items-start gap-2">
                    <Sparkles className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="text-sm font-semibold text-green-900">AI Processing Includes:</p>
                      <ul className="text-sm text-gray-700 mt-2 space-y-1">
                        <li>• Medical terminology validation</li>
                        <li>• Structured formatting (Lungs, Mediastinum, etc.)</li>
                        <li>• Clinical impression generation</li>
                        <li>• Recommendation synthesis</li>
                      </ul>
                    </div>
                  </div>
                </div>

                {isGenerating ? (
                  <div className="bg-gradient-to-r from-green-50 to-blue-50 border-2 border-green-300 rounded-lg p-6 text-center">
                    <Loader2 className="w-8 h-8 text-green-600 animate-spin mx-auto mb-3" />
                    <p className="font-semibold text-gray-900">Generating your report...</p>
                    <p className="text-sm text-gray-600 mt-1">AI is processing findings and validating clinical accuracy</p>
                    <div className="mt-4 space-y-2">
                      <div className="flex items-center justify-center gap-2 text-sm text-gray-700">
                        <CheckCircle className="w-4 h-4 text-green-600" />
                        <span>Analyzing findings</span>
                      </div>
                      <div className="flex items-center justify-center gap-2 text-sm text-gray-700">
                        <Loader2 className="w-4 h-4 text-green-600 animate-spin" />
                        <span>Validating terminology</span>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="flex justify-between">
                    <Button onClick={handleBack} variant="outline">
                      Back
                    </Button>
                    <Button onClick={handleGenerate} className="bg-green-600 hover:bg-green-700">
                      Generate Report
                      <Sparkles className="ml-2 w-4 h-4" />
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>
          </motion.div>
        )}

        {/* Step 4: Review & Export */}
        {currentStep === 4 && generatedReport && (
          <motion.div
            key="step4"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            <Card className="border-2 border-orange-200">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <Download className="w-6 h-6 text-orange-600" />
                  Step 4: Review & Export
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="bg-green-50 border-l-4 border-green-500 p-4 rounded">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-green-600" />
                    <p className="font-semibold text-green-900">Report Generated Successfully!</p>
                  </div>
                  <p className="text-sm text-gray-700 mt-1">
                    Clinical accuracy validated • Professional formatting applied
                  </p>
                </div>

                <div className="bg-gray-50 border border-gray-300 rounded-lg p-4 max-h-96 overflow-y-auto">
                  <pre className="text-xs font-mono whitespace-pre-wrap text-gray-800">
                    {generatedReport}
                  </pre>
                </div>

                <div className="flex justify-between items-center">
                  <Button onClick={handleReset} variant="outline" className="gap-2">
                    <RotateCcw className="w-4 h-4" />
                    Start Over
                  </Button>
                  <div className="flex gap-2">
                    <Button onClick={handleBack} variant="outline">
                      Back
                    </Button>
                    <Button onClick={handleDownload} className="bg-orange-600 hover:bg-orange-700">
                      Download Report
                      <Download className="ml-2 w-4 h-4" />
                    </Button>
                  </div>
                </div>

                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                  <p className="text-sm text-gray-700">
                    <span className="font-semibold text-blue-700">Note:</span> This is a demo. In the real app, you'll get a professionally formatted DOCX file ready for your PACS system.
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Time Indicator */}
      <div className="mt-6 text-center">
        <div className="inline-flex items-center gap-2 bg-gray-100 px-4 py-2 rounded-full text-sm text-gray-700">
          <Clock className="w-4 h-4 text-gray-600" />
          <span>
            Demo Step {currentStep} of 4
            {currentStep === 4 && generatedReport && " - Complete!"}
          </span>
        </div>
      </div>
    </div>
  );
}
