require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapgoCapacitorSocialLogin', :path => '../../node_modules/@capgo/capacitor-social-login'
  pod 'RadlyCapacitorGoogleAuth', :path => '../../../radly-google-auth'
  pod 'CapacitorVoiceRecorder', :path => '../../node_modules/capacitor-voice-recorder'
end

target 'App' do
  capacitor_pods
  # Native Google Sign-In for custom plugin
  pod 'GoogleSignIn'
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  # Relax warnings from Cordova bridge headers so they don't fail the build
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |bc|
      bc.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      bc.build_settings['CLANG_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      bc.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      bc.build_settings['ENABLE_MODULE_VERIFIER'] = 'NO'  # Disable for pods to avoid GTMSessionFetcher errors
      # Silence third-party Pods warnings to keep Xcode output clean
      bc.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      bc.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
    end
  end

  # Also update the App project so Xcode 15 script sandboxing doesn't block CocoaPods phases
  begin
    require 'xcodeproj'
    app_proj_path = File.join(__dir__, 'App.xcodeproj')
    if File.exist?(app_proj_path)
      app_project = Xcodeproj::Project.open(app_proj_path)
      app_project.targets.each do |t|
        next unless t.name == 'App'
        t.build_configurations.each do |bc|
          bc.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
          bc.build_settings['CLANG_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          bc.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        end
      end
      app_project.save
    end
  rescue => e
    puts "[Podfile post_install] Skipped App.xcodeproj patch: #{e}"
  end
end
